"""常量定义"""

# API 版本
API_VERSION = "v1"

# 默认分页大小
DEFAULT_PAGE_SIZE = 20

# 应用包相关
MAX_PACKAGE_SIZE = 100 * 1024 * 1024  # 100MB
MANIFEST_FILE_NAME = "manifest.json"

# 发布状态
PUBLISH_STATUS_UNPUBLISHED = 0
PUBLISH_STATUS_PUBLISHED = 1
PUBLISH_STATUS_UNPUBLISHED_UPDATE = 2

# 开发模式
DEV_MODE_UPLOAD = 1
DEV_MODE_ONLINE = 2

